version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/DublinBus

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: Decrypt release properties
          command: openssl aes-256-cbc -e -in key/keystore.properties -out key/keystore.properties-cipher -md sha256 -k $CIPHER_DECRYPT_KEY

      - run:
          name: Decrypt release key
          command: openssl aes-256-cbc -d -in key/keystore.properties-cipher -out key/keystore.properties -md sha256 -k $CIPHER_DECRYPT_KEY

      - run:
          name: Build
          command: ./gradlew assembleProd

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
